import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {randomBytes,createHash} from 'node:crypto';
import {fixture} from './core-test.mjs';import {dispatch} from '../backend/core.mjs';import {makeCrypto} from '../backend/crypto.mjs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/oofth/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=fileURLToPath(new URL('../site/',import.meta.url)),out=path.join(os.tmpdir(),'st-github-drive-qa');fs.mkdirSync(out,{recursive:true});
const db=fixture(),cryptoApi=makeCrypto({encode:s=>new TextEncoder().encode(s),hash:s=>createHash('sha256').update(s).digest('hex'),random:()=>randomBytes(32).toString('hex')});
const server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://localhost').pathname.replace(/^\/Saint-PP\.5\//,'');let file=path.join(root,rel||'index.html');if(!path.extname(file))file=path.join(file,'index.html');if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.html')?'text/html;charset=utf-8':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/javascript');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(5241,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1365,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.exposeFunction('qaRpc',request=>{try{const v=dispatch(db,request,cryptoApi);return {status:v.__error||200,body:v};}catch(e){return {status:e.status||400,body:{error:e.message}}}});
// Only Google's hosting/RPC endpoint is simulated; the production iframe transport and message checks execute unchanged.
await page.context().exposeFunction('qaGoogleRpc',request=>{try{const v=dispatch(db,request,cryptoApi);return {status:v.__error||200,body:v};}catch(e){return {status:e.status||400,body:{error:e.message}}}});
await page.route('**/cloud-config.js',route=>route.fulfill({contentType:'text/javascript',body:"window.ST_CLOUD_CONFIG={endpoint:'https://script.google.com/macros/s/QA_TEST_ONLY/exec'};"}));
await page.route('https://script.google.com/macros/s/QA_TEST_ONLY/exec*',route=>{const nonce=new URL(route.request().url()).searchParams.get('channel');return route.fulfill({contentType:'text/html',body:'<iframe src="https://qa-test.script.googleusercontent.com/bridge?channel='+nonce+'"></iframe>'})});
await page.route('https://qa-test.script.googleusercontent.com/**',route=>{const nonce=new URL(route.request().url()).searchParams.get('channel');let html=fs.readFileSync(new URL('../backend/Bridge.html',import.meta.url),'utf8').replace('<?!= JSON.stringify(origin) ?>',JSON.stringify('http://127.0.0.1:5241')).replace('<?!= JSON.stringify(channel) ?>',JSON.stringify(nonce));html=html.replace('<script>',`<script>window.google={script:{run:{withSuccessHandler(fn){this.success=fn;return this},withFailureHandler(fn){this.failure=fn;return this},stRpc(request){const ok=this.success,bad=this.failure;window.qaGoogleRpc(request).then(ok,bad)}}}};</script><script>`);return route.fulfill({contentType:'text/html',body:html});});

try{
 await page.goto('http://127.0.0.1:5241/Saint-PP.5/');await page.locator('#login-choice').selectOption('teacher');await page.locator('#teacher-query').fill('Teacher');await page.getByRole('button',{name:/Teacher QA/}).click();await page.locator('#password').fill('Synthetic-test-password');await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await page.waitForURL('**/app.html');await page.waitForFunction(()=>document.querySelector('#team-state')?.textContent.includes('ข้อมูลล่าสุด'));
 await page.evaluate(()=>{TERM=1;nav('scores')});await page.locator('[data-student=s1][data-slot="0"]').fill('5');await page.locator('[data-student=s1][data-slot="3"]').fill('10');await page.locator('[data-student=s1][data-kind=mid]').fill('24');await page.locator('[data-student=s1][data-kind=fin]').fill('27');assert.equal(await page.locator('[data-summary=s1] [data-total]').innerText(),'71');await page.locator('#is-save').click();await page.waitForFunction(()=>document.querySelector('#is-status')?.textContent.includes('บันทึกคะแนนส่วนกลางแล้ว'));
 await page.screenshot({path:path.join(out,'teacher-scores.png')});await page.reload();await page.waitForFunction(()=>document.querySelector('#team-state')?.textContent.includes('ข้อมูลล่าสุด'));await page.evaluate(()=>{TERM=1;nav('scores')});assert.equal(await page.locator('[data-summary=s1] [data-total]').innerText(),'71');
 await page.setViewportSize({width:390,height:844});await page.locator('#score-four-config').click();await page.screenshot({path:path.join(out,'mobile-parts.png')});assert(await page.locator('#indicator-plan-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));assert.deepEqual(errors,[]);
 console.log('PASS GitHub subpath login, teacher assignment scope, four-part entry/save/reload, mobile configuration, no browser runtime errors. Production iframe transport tested against simulated Google RPC; live Google deployment still pending.');
}catch(e){console.log('QA debug',errors,await page.locator('body').innerText(),page.frames().map(f=>f.url()));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
