import assert from 'node:assert/strict';import {randomBytes,createHash,scryptSync} from 'node:crypto';
import {dispatch} from '../backend/core.mjs';import {makeCrypto,seal,open} from '../backend/crypto.mjs';import {pack} from '../backend/legacy-model.mjs';
const encode=s=>new TextEncoder().encode(s),decode=a=>new TextDecoder().decode(a),hash=s=>createHash('sha256').update(s).digest('hex'),random=()=>randomBytes(32).toString('hex'),c=makeCrypto({encode,hash,random});
const pw='Synthetic-test-password',salt='migration-test-salt',oldHash=scryptSync(pw,salt,64).toString('hex');assert.equal(c.password(pw,salt),oldHash);assert(c.verify(pw,salt,oldHash));assert(!c.verify('incorrect',salt,oldHash));
const items=[{id:'before',text:'Before indicator',entryMode:'total',max:[10,0,0],passPercent:50,stage:'before'},{id:'after',text:'After indicator',entryMode:'total',max:[20,0,0],passPercent:50,stage:'after'}];
export const fixture=()=>{const data={lk3_school:{name:'Test School',adminPin:'not-public'},lk3_classes:[{id:'c1',level:'ม.1',room:'1',year:'2569',scoreMode:'sec'},{id:'c2',level:'ป.1',room:'1',year:'2569',scoreMode:'p100'}],lk3_c1_students:[{id:'s1',no:1,fname:'Test',lname:'Student'}],lk3_c1_subjects:[{id:'math',name:'Math',code:'ค21101',vterm:'1',wt:70,wf:30,wmid:30,slots:6,group:'คณิตศาสตร์',type:'พื้นฐาน',credit:1,hours:40},{id:'thai',name:'Thai',vterm:'1',wt:70,wf:30,wmid:30}],lk3_c2_students:[{id:'s2',fname:'Hidden'}],lk3_c2_subjects:[{id:'science',name:'Science'}],lk3_c1_desc:{math:{indicators:'Before indicator\nAfter indicator',scorePlan:{version:1,items,fourParts:{before:20,mid:30,after:20,final:30}}}}};const records=pack(data);return {format:'SaintTheresaDriveDB1',generation:0,users:[{id:'a',username:'admin',name:'Admin QA',role:'admin',active:1,salt,hash:oldHash},{id:'t',username:'teacher',name:'Teacher QA',role:'teacher',active:1,salt,hash:oldHash}],grants:[{uid:'t',cid:'c1',sid:'math'}],records,revisions:Object.fromEntries(Object.keys(records).map(k=>[k,1])),sessions:{},attempts:{},audit:[]};};
const db=fixture();function call(path,body,token,status=200){let result;try{result=dispatch(db,{path,method:body?'POST':'GET',body,token},c);}catch(e){assert.equal(e.status||400,status,e.message);return;}assert.equal(result?.__error||200,status);return result;}
const admin=call('/api/login',{username:'admin',password:pw}).token,teacher=call('/api/login',{username:'teacher',password:pw}).token;
call('/api/legacy',null,null,401);call('/api/users',null,teacher,403);const view=call('/api/legacy',null,teacher);assert.equal(view.records['["lk3_classes"]'].length,1);assert.equal(view.records['["lk3_c1_subjects"]'].length,1);for(const secret of ['not-public','Hidden',oldHash])assert(!JSON.stringify(view).includes(secret));
const id='["lk3_c1_scores","s1","math"]',value={t1slots:[5,'','',10],t1mraw:80,t1fraw:90};call('/api/legacy',{operations:[{id,rev:0,value}]},teacher);call('/api/legacy',{operations:[{id,rev:0,value}]},teacher,409);assert.deepEqual(db.records[id],value);
call('/api/legacy',{operations:[{id:'["lk3_c1_scores","s1","thai"]',rev:0,value}]},teacher,403);
const before=JSON.stringify(db.records);call('/api/legacy',{operations:[{id,rev:1,value:{...value,t1slots:[99]}}]},teacher,400);assert.equal(JSON.stringify(db.records),before);
call('/api/legacy',{operations:[{id,rev:1,value},{id:'["lk3_c2_students"]',rev:1,value:[]}]},teacher,403);assert.equal(JSON.stringify(db.records),before);
const planId='["lk3_c1_desc","math"]',plan=structuredClone(db.records[planId]);plan.scorePlan.fourParts.final=20;call('/api/legacy',{operations:[{id:planId,rev:1,value:plan}]},teacher,400);call('/api/subject-weight',{cid:'c1',sid:'math',wt:80,rev:1},teacher,400);
call('/api/my-teaching',{cid:'c2',sid:'*'},teacher,403);call('/api/my-teaching',{cid:'c2',sid:'science'},teacher);call('/api/my-teaching',{cid:'c2',sid:'science'},teacher);assert.equal(db.grants.length,2);
call('/api/grant',{uid:'t',cid:'c2',sid:'science',remove:true},admin);assert.equal(call('/api/legacy',null,teacher).records['["lk3_classes"]'].length,1);
call('/api/user',{id:'t',password:'Replacement-test-password'},admin);call('/api/legacy',null,teacher,401);for(let i=0;i<8;i++)call('/api/login',{username:'teacher',password:'wrong'},null,401);call('/api/login',{username:'teacher',password:'wrong'},null,429);
const key=random(),encrypted=seal(db,key,random(),encode);assert(!JSON.stringify(encrypted).includes('Teacher QA'));assert.deepEqual(open(encrypted,key,decode),db);assert.throws(()=>open(encrypted,random(),decode));const tamper={...encrypted,ciphertext:encrypted.ciphertext.slice(0,-2)+(encrypted.ciphertext.endsWith('00')?'01':'00')};assert.throws(()=>open(tamper,key,decode));
console.log('PASS old passwords, scoped permissions, four-part scores, atomic rejection, conflicts, self-assignment, revocation, rate limits and encryption');
